### ISSUE TITLE
How do I create an action on send like UIAlertView?

### ISSUE THREAD

**Issue by ahwestrich** [lmcd/LMAlertView#12]
How can I call a delegate method like in UIAlertView?
For example:
LMAlertView *alert = [[LMAlertView alloc] initWithTitle:@"Are you sure you want to send?"
                                                        message:theMessage
                                                       delegate:self
                                              cancelButtonTitle:@"Cancel"
                                              otherButtonTitles:@"Send", nil];
in UIAlertView, this method is called:
- (void)alertView:(UIAlertView *)alertView
  clickedButtonAtIndex:(NSInteger)buttonIndex{...

What's the equivalent in LMAlertView?

Thank you,
Adam

**Comment by lmcd** [comment]
Whoops, this was a bug. It's now been fixed and implemented in the demo.
