### ISSUE TITLE
QUESTION: Strange Syntax?

### ISSUE THREAD

**Issue by Pintiboy** [lmcd/LMAlertView#15]
Hi there,

one question to one line of the code:

In line 241 of LMAlertView.m you write

_alertContainerView = [[UIView alloc] initWithFrame:(CGRect){.size = [[UIScreen mainScreen] bounds].size}];

I have to say that I never saw this syntax before. I even googled it and haven't found anything similar. I'm talking about "(CGRect){.size =" Can you explain how and why this works?

Greets from Germany
Andi

**Comment by lmcd** [comment]
Just a shorthand for defining a `CGRect`, or any other struct :)
I use it here as the origin is 0,0 (or `CGPointZero`!), so I don't bother declaring it.

The syntax came about in C99. See here: http://www.dribin.org/dave/blog/archives/2010/05/15/c99_syntax/
