### ISSUE TITLE
Crashed on device when installed via test flight

### ISSUE THREAD

**Issue by BryonApps** [lmcd/LMAlertView#18]
Has anyone seen this?

I have no problems when I run on device via Xcode.  Deploy via an archive via test flight and I get a crash after init w/ title.  Looks to be related to [CALayer setPosition:] call...

![screen shot 2013-12-11 at 8 28 48 pm](https://f.cloud.github.com/assets/761461/1730158/792de380-62d5-11e3-92bc-94f6d4778a05.png)

**Comment by lmcd** [comment]
Yes, sorry this has been reported by someone else also. Will fix this evening.

**Comment by BryonApps** [comment]
No worries!  Love what you've done here - very helpful!  
Oh, you also might want to make sure the delegate is getting set when you pass one in via init with title, etc.

**Comment by lmcd** [comment]
@BryonApps this should be fixed now!

**Comment by BryonApps** [comment]
Great!  I'll check it out today!!

Bryon Martin

(Sent from my iPhone)
