### ISSUE TITLE
The CAAnimation+Blocks needs a reference in the README

### ISSUE THREAD

**Issue by dhoerl** [lmcd/LMAlertView#20]
If your project is going to depend on another open source project, please add a URL to the README. I don't use CocoaPods, and so I find one using google, but not sure if its the right one (got lots of hits).

Also, why:
# import

and not
# import "CAAnimation+Blocks.h"

The former implies this is a System header file, not a User one.

**Comment by lmcd** [comment]
Good catch, I added `CAAnimation+Blocks` on a whim and it ended up in master. Forgot to credit.

**Comment by lmcd** [comment]
Fixed.
P.S. it might be worth checking out CocoaPods. It saves a great deal of time!
