### ISSUE TITLE
One analysis warning in the brand new DP2 Xcode on uninitialized data

### ISSUE THREAD

**Issue by dhoerl** [lmcd/LMAlertView#22]
CGRect frame;
frame.size = size;
// frame.origin is unitialized. Yeah, its just a spurious warning but thought I'd post it anyway!  
_representationView = [[UIView alloc] initWithFrame:frame];

This fixes it (syntax is yours, I just saw it for the first time today! Nice! :-)
frame = (CGRect){.size = size};

**Comment by lmcd** [comment]
Thanks :) Fixed.
