### ISSUE TITLE
Modaltransformanimation completionblock selector not recognized

### ISSUE THREAD

**Issue by leetal** [lmcd/LMAlertView#32]
Hi!

Just installed this via cocoapods (pointed to this github for latest release). I get an error in LMAlertView.m on row 473 saying that: -[RBBSpringAnimation setCompletion:]: unrecognized selector sent to instance XXXX. 

By removing that block, the alertview does show up and seems to work. But obviously the didPresentAlertView in the delegate is not called upon the animation completion. It might just be some reference problem locally, but as it seems to find the CAAnimationBlocks library and not the setter, something is obviously not ok :)
The headers are there since i don't get any compilation errors.

Regards 
Alex

**Comment by lmcd** [comment]
Hmm strange, the only reasonable explanation is `CAAnimationBlocks` not being present - but you say that it is :\
Have you tried with 1.1.0?

**Comment by leetal** [comment]
Yes, it's the same thing in both. :S Tried to correct it, but were unable
to.. Everything else is working, except that :/

2014/1/8 Lee M notifications@github.com

**Comment by lmcd** [comment]
I'd say look a little more closely at your project and the way it's configured. I doubt this is a problem with `LMAlertView`. Is Target Membership set correctly on `CAAnimationBlocks`?

**Comment by leetal** [comment]
To sum this up: I ended up just copying the CAAnimation-Blocks.m/h to my own project and set the compile-flag to -fobjc-arc. This fixed the problem, but it's definitely not the right way of doing it. I just couldn't get it to link the CAAnimation+Blocks file correctly (didn't build the .m file). So there's evidently a problem with the target membership throughout cocoapods linking-process. I think it has something to do with that the category imports a static library and thus will not link the files correctly while compiling.
