### ISSUE TITLE
A way to dismiss the alertview

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [lmcd/LMAlertView#39]
First off, thanks for the awesome library. The rating control alone helped me a ton :+1: 

I have a small problem. I have another instance of the LMAlertView with 2 custom buttons which looks like this,

![ios simulator screen shot apr 3 2014 10 50 03 pm](https://cloud.githubusercontent.com/assets/2551877/2606809/46d41e4e-bb55-11e3-8183-ef7213394dfb.png)

Clicking on either of those buttons bring up a SLComposeViewController. Now my problem is when I click on those buttons, the compose view controller appears under the alert view. Like so,

![ios simulator screen shot apr 3 2014 10 50 09 pm](https://cloud.githubusercontent.com/assets/2551877/2606825/6cf7a74e-bb55-11e3-9efb-012c423bf687.png)

If there's a method (like show) to dismiss the alert view, that would be great. 

Thank you.

**Comment by Isuru-Nanayakkara** [comment]
Okay I was too quick. Just check out the header file and found this method that works. 
- (void)dismissWithClickedButtonIndex:(NSInteger)buttonIndex animated:(BOOL)animated

**Comment by YevTarler** [comment]
I've noticed your LMAlertView isn't transparent. Did you managed to fix this ?

**Comment by Isuru-Nanayakkara** [comment]
@YevTarler Actually no. It didn't really bother me that much. Frankly I noticed it when you just mentioned it!
