### ISSUE TITLE
Cannot create an instance of LMAlertView in Swift

### ISSUE THREAD

**Issue by asiby** [lmcd/LMAlertView#58]
When the following code runs ...

```
var lmAlertView: LMAlertView = LMAlertView(title: "Titre", message: "Message", delegate: self, cancelButtonTitle: "Annuler")
```

... it crashes the App with the following error message ...

```
[LMAlertView initWithTitle:message:delegate:cancelButtonTitle:]: unrecognized selector sent to instance 0x7f85e0472b10
```

Even worse, when I try to add additional buttons but using the otherButtonTitles arguments like this ...

```
var lmAlertView: LMAlertView = LMAlertView(title: "Titre", message: "Message", delegate: self, cancelButtonTitle: "Cancel", otherButtonTitles: "OK")
```

... then the App will not even compile. I get the following error message:

```
Extra argument 'message' in call
```

In that case, I think that it's because it didn't find the signature of function that contains otherButtonTitles, it is trying to default to the one where you pass a view controller to LMAlertView() ... with 1 single argument.

Has anyone had this kind of problem? Can someone direct me to an example that shows how to use LMAlertView with Swift please?

Thanks everyone.

El Mouhandiss

**Comment by ay8s** [comment]
Changing the following line seems to get things to work for me in Swift. Will dig into it more later.

```
- (id)initWithTitle:(NSString *)title message:(NSString *)message delegate:(id)delegate cancelButtonTitle:(NSString *)cancelButtonTitle otherButtonTitles:(NSString *)otherButtonTitles, ... NS_REQUIRES_NIL_TERMINATION;
```

Change to:

```
- (id)initWithTitle:(NSString *)title message:(NSString *)message delegate:(id)delegate cancelButtonTitle:(NSString *)cancelButtonTitle otherButtonTitles:(NSString *)otherButtonTitles;
```

**Comment by asiby** [comment]
Thanks @ay8s

**Comment by CaiWanFeng** [comment]
@ay8s Do you know the reason now?

**Comment by ztalbot2000** [comment]
I use it only because my Apps are for people with visual disabilities and I
need to make alert messages really big.

Ttfn,
John
